{{- if .Values.huggingFaceToken }}
apiVersion: v1
data:
  hf_api_token: {{ .Values.huggingFaceToken | b64enc }}
kind: Secret
metadata:
  name: hf-secret
  namespace: {{ .Release.Namespace }}
{{- end }}
