{{- if .Values.backend.enabled -}}
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: {{ include "gpt-sample-app.fullname" . }}
  labels:
    {{- include "gpt-sample-app.labels" . | nindent 4 }}
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - {{ .Values.kafka.bootstrap }}:{{ .Values.kafka.externalPort }}
  topics:
  - OSSEvents
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: {{ include "gpt-sample-app.fullname" . }}
{{- end }}