apiVersion: v1
kind: Secret
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-minio-artifact
type: Opaque
stringData:
  accesskey: {{ .Values.bucket.accesskey }} 
  secretkey: {{ .Values.bucket.secretkey }}