apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
data:
  config: |
    {
        artifactRepository: {
            s3: {
                bucket: nkp3-kf-mlpipeline,
                keyPrefix: artifacts,
                endpoint: objects.romanticism.cloudnative.nvdlab.net,
                insecure: true,
                accessKeySecret: {
                    name: mlpipeline-minio-artifact,
                    key: accesskey
                },
                secretKeySecret: {
                    name: mlpipeline-minio-artifact,
                    key: secretkey
                }
            },
            archiveLogs: true
        }
    }
