{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpt-sample-app.fullname" . }}
  labels:
    {{- include "gpt-sample-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpt-sample-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpt-sample-app.labels" . | nindent 8 }}
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- with .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: "MILVUS_HOST"
              value: {{ .Values.milvus.host | quote }}
            - name: "MILVUS_PORT"
              value: {{ .Values.milvus.port | quote }}
            - name: "MILVUS_COLLECTION"
              value: {{ .Values.milvus.collection | quote }}
            - name: "INFERENCE_ENDPOINT"
              value: {{ .Values.inference.endpoint | quote }}
            - name: "SSL_VERIFY"
              value: {{ .Values.s3.sslVerify | quote }}
            - name: "S3_REGION"
              value: {{ .Values.s3.region | quote }}
            - name: "ACCESS_KEY"
              value: {{ .Values.s3.accessKey | quote }}
            - name: "SECRET_KEY"
              value: {{ .Values.s3.secretKey | quote }}
            - name: "S3_ENDPOINT_URL"
              value: {{ .Values.s3.endpoint | quote }}
            - name: "BUCKET_NAME"
              value: {{ .Values.s3.bucket | quote }}
          {{- range .Values.frontend.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
      {{- with .Values.frontend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}