{{- if .Values.backend.enabled -}}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "gpt-sample-app.fullname" . }}
  labels:
    {{- include "gpt-sample-app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1" 
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: "MILVUS_HOST"
              value: {{ .Values.milvus.host | quote }}
            - name: "MILVUS_PORT"
              value: {{ .Values.milvus.port | quote }}
            - name: "MILVUS_COLLECTION"
              value: {{ .Values.milvus.collection | quote }}
            - name: "INFERENCE_ENDPOINT"
              value: {{ .Values.inference.endpoint | quote }}
            - name: "SSL_VERIFY"
              value: {{ .Values.s3.sslVerify | quote }}
            - name: "S3_REGION"
              value: {{ .Values.s3.region | quote }}
            - name: "ACCESS_KEY"
              value: {{ .Values.s3.accessKey | quote }}
            - name: "SECRET_KEY"
              value: {{ .Values.s3.secretKey | quote }}
            - name: "S3_ENDPOINT_URL"
              value: {{ .Values.s3.endpoint | quote }}
            - name: "BUCKET_NAME"
              value: {{ .Values.s3.bucket | quote }}
          {{- range .Values.backend.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end }}