{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpt-sample-app.fullname" . }}-svc
  labels:
    {{- include "gpt-sample-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gpt-sample-app.selectorLabels" . | nindent 4 }}
{{- end }}