apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - kafka.gpt01mgmt01.cloudnative.nvdlab.net:9096 # note the kafka namespace
  topics:
  - OSSEvents
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: doc-ingest